book: Fix main_event_loop_7 runtime error
Let ashpd use async-std so the main_event_loop_7 example can run.

Fixed runtime error:

     Running `target/debug/main_event_loop_7`

thread 'main' (440572) panicked at /home/gang/.cargo/registry/src/mirrors.ustc.edu.cn-38d0e5eb5da2abae/zbus-5.8.0/src/abstractions/executor.rs:189:27:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace